# -*- coding: utf-8 -*-
"""Juego de pica y fija

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBO-LjmI2ykhsYyQEKVzb1yyw89A252N

Juego de picas y fijas
Diana del Pilar Núñez Sandoval
20232010010
"""

import random

def juego_pica_fija():
  numero_secreto=str(random.randit(1000,9999))
  print("pica_fija")
  print("Numero de 4 dijitos")
  print("Fija: dígito correcto en posición correcta")
  print("Pica: dígito correcto en posición incorrecta")
  intentos=0

  while True:
    try:
       intento = input("Ingrese un numero de 4 dijitos:")

       if not intento.isdigit() or len(intento) != 4:
         print("Error: Debe ser un número de 4 dígitos")
         intentos += 1
         picas = 0
         fijas = 0

      for i in range(4)
           if intento [i]==numero_secreto[i]:
              fijas += 1
           elif intento[i] in numero_secreto:
               picas += 1

"""str- Es para comparar digito por digito
while co try para manejar el error de si no da el numero
el picas y fijas=0 es la indicacion que da si tiene

"""